In [174]:


import numpy as np

# adjacency matrix
# a = np.matrix('0 1 1; 1 0 1; 1 1 0')
a = np.matrix('0 1 1 1; 1 0 1 1 ; 1 1 0 1; 1 1 1 0')

def matEval(mat):
    
    # display matrix
    print('  ', end='')
    for i in range(0, len(mat)):
        print( chr(ord('a')+i), end=' ')
        
    print()
    print(mat, end='\n\n')
    
    # check if matrix is square, return if not
    if(mat.shape[0] != mat.shape[1]):
        print("Error: Matrix must be square.")
        return
    
    # display number of edges
    print("|V| =", len(mat))
    # display number of edges
    print("|E| =", np.sum(np.triu(mat)))
    
    print()
    # display degree of each vertex
    i = 0
    for row in mat:
        print(f"deg({chr(ord('a')+i)})",'=',np.sum(row))
        i+=1

matEval(a)

  a b c d 
[[0 1 1 1]
 [1 0 1 1]
 [1 1 0 1]
 [1 1 1 0]]

|V| = 4
|E| = 6

deg(a) = 3
deg(b) = 3
deg(c) = 3
deg(d) = 3
