In [331]:
# matEval will find/display:
# Number of edges, vertices
# degree of all vertices
# Neighborhoods for all vertices

import numpy as np

# adjacency matrix
# a = np.matrix('0 1 1; 1 0 1; 1 1 0')
a = np.matrix('0 1 1 1; 1 0 1 1 ; 1 1 0 1; 1 1 1 0')

def matEval(mat):
    
    # display matrix
    print('  ', end='')
    for i in range(0, len(mat)):
        print( chr(ord('a')+i), end=' ')
        
    print()
    print(mat, end='\n\n')
    
    # check if matrix is square, return if not
    if(mat.shape[0] != mat.shape[1]):
        print("Error: Matrix must be square.")
        return
    
    # display number of edges
    print("|V| =", len(mat))
    # display number of edges
    print("|E| =", np.sum(np.triu(mat)))
    
    print()
    
    # display degree of each vertex
    i = 0
    for row in mat:
        print(f"deg({chr(ord('a')+i)})",'=',np.sum(row))
        i+=1

matEval(a)

  a b c d 
[[0 1 1 1]
 [1 0 1 1]
 [1 1 0 1]
 [1 1 1 0]]

|V| = 4
|E| = 6

deg(a) = 3
deg(b) = 3
deg(c) = 3
deg(d) = 3


In [352]:
class Graph:
    
    def __init__(self, adjMat = np.matrix('0 1; 1 0')):
        # adjacency matrix
        self.adjMat = adjMat
        
        # vertices array
        self.vertices = [chr(ord('a')+ v) for v in range(len(adjMat))]
        
        # edges array
        self.edges = []
        
        # init edges array
        for i in range(len(self.adjMat)):
            for j in range(len(self.adjMat)):
                # if number of edges in mat > 0, concat characters in vertices array
                if np.array(np.triu(self.adjMat))[i][j] > 0:
                    self.edges.append(self.vertices[i]+self.vertices[j])
                    
    
    
    def __repr__(self):
        return "__repr__ called"
    
        
g = Graph(np.matrix('0 1 1;1 0 1; 1 1 0'))
g.vertices, g.edges

(['a', 'b', 'c'], ['ab', 'ac', 'bc'])