In [52]:
# matEval will find/display:
# Number of edges, vertices
# degree of all vertices
# Neighborhoods for all vertices

import numpy as np

# adjacency matrix
# a = np.matrix('0 1 1; 1 0 1; 1 1 0')
a = np.matrix('0 1 1 1; 1 0 1 1 ; 1 1 0 1; 1 1 1 0')

def matEval(mat):
    
    # display matrix
    print('  ', end='')
    for i in range(0, len(mat)):
        print( chr(ord('a')+i), end=' ')
        
    print()
    print(mat, end='\n\n')
    
    # check if matrix is square, return if not
    if(mat.shape[0] != mat.shape[1]):
        print("Error: Matrix must be square.")
        return
    
    # display number of edges
    print("|V| =", len(mat))
    # display number of edges
    print("|E| =", np.sum(np.triu(mat)))
    
    print()
    
    # display degree of each vertex
    i = 0
    for row in mat:
        print(f"deg({chr(ord('a')+i)})",'=',np.sum(row))
        i+=1

matEval(a)

  a b c d 
[[0 1 1 1]
 [1 0 1 1]
 [1 1 0 1]
 [1 1 1 0]]

|V| = 4
|E| = 6

deg(a) = 3
deg(b) = 3
deg(c) = 3
deg(d) = 3


In [67]:
class Graph:
    
    def __init__(self, adjMat = np.matrix('0 1; 1 0')):
        
        if adjMat.shape[0] != adjMat.shape[1]:
            print("Err: Adjacency matrix not square.")
            return

        if not np.array_equal(np.array(np.transpose(adjMat)), np.array(adjMat)):
            print("Err: Adjacency matrix not symmetrical.")
            return
        
        # adjacency matrix
        self.adjMat = adjMat
        
        # vertices array
        self.vertices = [chr(ord('a')+ v) for v in range(len(adjMat))]
        
        # edges array
        self.edges = []
        
        # init edges array
        for i in range(len(self.adjMat)):
            for j in range(len(self.adjMat)):
                
                # if number of edges in mat > 0, concat characters in vertices array
                for k in range(np.array(np.triu(self.adjMat))[i][j]):
                    self.edges.append(self.vertices[i] + self.vertices[j])
                    
        # degree of each vertex
        self.degrees = [sum(row) for row in np.array(adjMat)]
                    
    
    
    def __repr__(self):
        return f"Vertices: {self.vertices}\nDegrees: {self.degrees}\nEdges: {self.edges}"
    
# k4 = Graph(np.matrix('0 1 1 1; 1 0 1 1; 1 1 0 1; 1 1 1 0'))       
g = Graph(np.matrix('0 1 1;1 0 1; 1 1 0'))
g

Vertices: ['a', 'b', 'c']
Degrees: [2, 2, 2]
Edges: ['ab', 'ac', 'bc']